import pathlib
p = pathlib.Path('packages/ktools-media/src/ktools_media/node.py')
code = p.read_text('utf-8')

code = code.replace(
    "from .audio.split import split_audio",
    "from .audio.split import split_audio\nfrom .audio.join import join_audios"
)

register_call = """,
    )
    registry.register(
        NodeDefinition(
            type_id="media.join_audios",
            title="Join Audios",
            category="Media",
            inputs={
                "audios": PortDefinition(DataType.FILE_SET),
            },
            outputs={
                "audio": PortDefinition(DataType.AUDIO),
            },
            version="1",
            cache_policy=CachePolicy.NEVER,
        ),
        _join_audios_node,
    )"""

code = code.replace(",\n    )", register_call, 1)

new_func = """

def _join_audios_node(
    inputs: dict[str, Any], config: dict[str, Any], context: NodeExecutionContext
) -> dict[str, Any]:
    # audios could be a single FILE_SET artifact or a list of Artifacts
    audios = inputs.get("audios")
    if not audios:
        raise ValueError("media.join_audios requires 'audios' input.")
        
    artifacts = audios if isinstance(audios, list) else [audios]
    
    # We might need to handle if a FILE_SET artifact is passed with no payload vs list of files.
    # We assume 'audios' is a list of Artifact instances generated by a split or scan node.
    if len(artifacts) < 2:
        raise ValueError("media.join_audios requires at least 2 audio files in the set.")
        
    # Sort to ensure determinism
    artifacts = sorted(artifacts, key=lambda a: a.metadata.get("name", a.uri) if a.metadata else a.uri)
    
    input_paths = [path_from_file_uri(a.uri) for a in artifacts]
    
    out_format = config.get("format", "m4a").lower().strip(".")
    bitrate = config.get("bitrate")
    
    output_dir = input_paths[0].parent
    if "output_dir" in config:
        output_dir = Path(config["output_dir"])
        
    output_path = output_dir / f"joined_audio.{out_format}"
    
    counter = 1
    while output_path.exists():
        output_path = output_dir / f"joined_audio_{counter}.{out_format}"
        counter += 1
        
    final_path = join_audios(
        input_paths=input_paths,
        output_path=output_path,
        output_format=out_format,
        bitrate=bitrate,
    )
    
    from ktools_core.models import Artifact
    
    out_artifact = Artifact.create(
        type=DataType.AUDIO,
        uri=final_path.as_uri(),
        metadata={
            "name": final_path.name,
            "format": out_format,
            "size_bytes": final_path.stat().st_size,
        },
    )
    return {"audio": out_artifact}
"""
code += new_func
p.write_text(code, 'utf-8')
