from __future__ import annotations

import http.cookiejar
import time
from typing import Any, Mapping, Sequence

ALLOWED_GOOGLE_YOUTUBE_DOMAINS = (
    ".youtube.com",
    ".google.com",
    ".accounts.google.com",
    "youtube.com",
    "google.com",
)

AUTH_COOKIE_NAMES = {
    "LOGIN_INFO",
    "SID",
    "HSID",
    "SSID",
    "APISID",
    "SAPISID",
    "__Secure-1PSID",
    "__Secure-3PSID",
    "__Secure-1PAPISID",
    "__Secure-3PAPISID",
}


def is_domain_allowed(domain: str) -> bool:
    dom = domain.lower().lstrip(".")
    for allowed in ALLOWED_GOOGLE_YOUTUBE_DOMAINS:
        target = allowed.lower().lstrip(".")
        if dom == target or dom.endswith("." + target):
            return True
    return False


def cdp_cookies_to_cookiejar(cdp_cookies: Sequence[Mapping[str, Any]]) -> tuple[http.cookiejar.CookieJar, int]:
    """Filters CDP cookies to Google/YouTube domains and converts them to a standard CookieJar."""
    jar = http.cookiejar.CookieJar()
    kept = 0

    for raw in cdp_cookies:
        domain = str(raw.get("domain") or "").strip()
        if not is_domain_allowed(domain):
            continue

        name = str(raw.get("name") or "").strip()
        value = str(raw.get("value") or "")
        if not name:
            continue

        raw_expires = raw.get("expires")
        expires: int | None = None
        if raw_expires is not None:
            try:
                exp_int = int(float(raw_expires))
                if exp_int > 0:
                    expires = exp_int
            except (ValueError, TypeError):
                expires = None

        path = str(raw.get("path") or "/")
        secure = bool(raw.get("secure", True))
        http_only = bool(raw.get("httpOnly", False))
        same_site = str(raw.get("sameSite") or "")

        cookie = http.cookiejar.Cookie(
            version=0,
            name=name,
            value=value,
            port=None,
            port_specified=False,
            domain=domain,
            domain_specified=True,
            domain_initial_dot=domain.startswith("."),
            path=path,
            path_specified=True,
            secure=secure,
            expires=expires,
            discard=False,
            comment=None,
            comment_url=None,
            rest={"HttpOnly": http_only, "SameSite": same_site},
            rfc2109=False,
        )
        jar.set_cookie(cookie)
        kept += 1

    return jar, kept


def inspect_cookiejar_auth(jar: http.cookiejar.CookieJar | None) -> dict[str, Any]:
    """Checks presence of essential authentication tokens and expiration."""
    if not jar:
        return {"has_auth": False, "active": False, "expired": False, "auth_count": 0}

    now = int(time.time())
    auth_found = 0
    live_found = 0

    for c in jar:
        if c.name in AUTH_COOKIE_NAMES:
            auth_found += 1
            if c.expires is None or c.expires == 0 or c.expires > now:
                live_found += 1

    has_auth = auth_found > 0
    active = live_found > 0
    expired = has_auth and (live_found == 0)

    return {
        "has_auth": has_auth,
        "active": active,
        "expired": expired,
        "auth_count": auth_found,
        "live_count": live_found,
    }


def cookiejar_to_netscape_text(jar: http.cookiejar.CookieJar) -> str:
    """Renders CookieJar into standard Netscape format string in memory."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by K-Tools Neo CDP Bridge"]
    for c in jar:
        domain = c.domain
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.path or "/"
        secure = "TRUE" if c.secure else "FALSE"
        expires = str(c.expires or 0)
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c.name}\t{c.value}")
    return "\n".join(lines) + "\n"
