import { type Node, type Edge } from '@xyflow/react';

export interface WorkflowPreset {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  expectedOutput: {
    fileName: string;
    description: string;
    path: string;
  };
  nodes: Node[];
  edges: Edge[];
}

export const WORKFLOW_PRESETS: WorkflowPreset[] = [
  {
    id: 'youtube-to-drive-audio',
    name: '🎬 Da Pasta de Vídeos ao Áudio Unificado no Google Drive',
    description: 'Localiza todos os vídeos (ex: baixados do YouTube), extrai as faixas de áudio, junta tudo em um só arquivo na ordem correta e salva no Google Drive.',
    category: 'Mídia & Nuvem',
    icon: '🎬',
    expectedOutput: {
      fileName: 'Audio_Consolidado_Playlist.wav',
      description: 'Áudio único unificado com volume normalizado de todos os vídeos',
      path: 'G:/Meu Drive/Audios_KTools/Audio_Consolidado_Playlist.wav',
    },
    nodes: [
      {
        id: 'step-1',
        type: 'ktool',
        position: { x: 50, y: 140 },
        data: {
          type_id: 'folder.literal',
          stepNumber: 1,
          label: 'Passo 1: Pasta dos Vídeos',
          category: 'Arquivos',
          description: 'Onde estão salvos os vídeos no seu computador.',
          inputs: [],
          outputs: [{ id: 'folder', type: 'folder', label: '📁 Pasta de Origem' }],
          config: { path: 'C:/Downloads/YouTube_Playlist' },
          runState: 'IDLE',
        },
      },
      {
        id: 'step-2',
        type: 'ktool',
        position: { x: 380, y: 140 },
        data: {
          type_id: 'folder.scan_files',
          stepNumber: 2,
          label: 'Passo 2: Localizar Vídeos',
          category: 'Arquivos',
          description: 'Encontra automaticamente todos os vídeos da pasta.',
          inputs: [{ id: 'folder', type: 'folder', label: '📁 Pasta para Varrer' }],
          outputs: [
            { id: 'files', type: 'files', label: '📚 Vídeos Encontrados' },
            { id: 'report', type: 'json', label: '📊 Relatório' },
          ],
          config: { extensions: 'mp4, mkv, webm', recursive: true },
          runState: 'IDLE',
        },
      },
      {
        id: 'step-3',
        type: 'ktool',
        position: { x: 720, y: 140 },
        data: {
          type_id: 'media.extract_audio',
          stepNumber: 3,
          label: 'Passo 3: Extrair Áudio (WAV)',
          category: 'Mídia',
          description: 'Extrai o áudio de cada vídeo com qualidade máxima.',
          inputs: [{ id: 'file', type: 'file', label: '🎬 Vídeo de Entrada' }],
          outputs: [{ id: 'audio', type: 'audio', label: '🎵 Áudios Extraídos' }],
          config: { format: 'wav', sample_rate: 44100 },
          runState: 'IDLE',
        },
      },
      {
        id: 'step-4',
        type: 'ktool',
        position: { x: 1060, y: 140 },
        data: {
          type_id: 'media.merge_audio_studio',
          stepNumber: 4,
          label: 'Passo 4: Juntar em Arquivo Único',
          category: 'Mídia',
          description: 'Une todas as faixas em sequência e normaliza o volume.',
          inputs: [{ id: 'files', type: 'files', label: '📚 Áudios para Unir' }],
          outputs: [{ id: 'output_file', type: 'file', label: '✨ Áudio Final Consolidado' }],
          config: {
            output_name: 'Audio_Consolidado_Playlist.wav',
            normalize: true,
          },
          runState: 'IDLE',
        },
      },
      {
        id: 'step-5',
        type: 'ktool',
        position: { x: 1400, y: 140 },
        data: {
          type_id: 'system.notify',
          stepNumber: 5,
          label: 'Passo 5: Avisar no Windows',
          category: 'Sistema',
          description: 'Envia um alerta na barra de tarefas ao terminar.',
          inputs: [{ id: 'trigger', type: 'any', label: '⚡ Sinal de Término' }],
          outputs: [{ id: 'delivered', type: 'boolean', label: '✓ Alerta Enviado' }],
          config: {
            title: 'K-Tools Neo — Processamento Concluído',
            message: 'Seu áudio unificado foi salvo com sucesso no Google Drive!',
          },
          runState: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'step-1', target: 'step-2', sourceHandle: 'folder', targetHandle: 'folder', animated: true, style: { stroke: '#eab308', strokeWidth: 2 } },
      { id: 'e2-3', source: 'step-2', target: 'step-3', sourceHandle: 'files', targetHandle: 'file', animated: true, style: { stroke: '#38bdf8', strokeWidth: 2 } },
      { id: 'e3-4', source: 'step-3', target: 'step-4', sourceHandle: 'audio', targetHandle: 'files', animated: true, style: { stroke: '#c084fc', strokeWidth: 2 } },
      { id: 'e4-5', source: 'step-4', target: 'step-5', sourceHandle: 'output_file', targetHandle: 'trigger', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
  {
    id: 'voice-master-alac',
    name: '🎙️ Masterização de Voz (De-Esser + Áudio Sem Perdas ALAC)',
    description: 'Limpa sibilância e chiados da gravação de voz e converte para M4A Apple Lossless economizando espaço com fidelidade bit-a-bit.',
    category: 'Áudio & Voz',
    icon: '🎙️',
    expectedOutput: {
      fileName: 'Voz_Masterizada_Lossless.m4a',
      description: 'Áudio masterizado sem ruídos em formato Apple Lossless (ALAC)',
      path: 'C:/Users/Public/Music/Voz_Masterizada_Lossless.m4a',
    },
    nodes: [
      {
        id: 'vm-1',
        type: 'ktool',
        position: { x: 80, y: 150 },
        data: {
          type_id: 'files.literal',
          stepNumber: 1,
          label: 'Passo 1: Áudio de Voz Bruto',
          category: 'Arquivos',
          description: 'Arquivo de gravação do microfone.',
          inputs: [],
          outputs: [{ id: 'files', type: 'files', label: '📚 Áudio Original' }],
          config: { paths: 'gravacao_microfone_take1.wav' },
          runState: 'IDLE',
        },
      },
      {
        id: 'vm-2',
        type: 'ktool',
        position: { x: 440, y: 150 },
        data: {
          type_id: 'media.deess_audio',
          stepNumber: 2,
          label: 'Passo 2: Limpar Voz (De-Esser)',
          category: 'Mídia',
          description: 'Atenua sons agudos incômodos e chiados.',
          inputs: [{ id: 'file', type: 'file', label: '🎵 Áudio Bruto' }],
          outputs: [{ id: 'output_file', type: 'file', label: '✨ Áudio Limpo' }],
          config: { intensity: 0.5, denoise: true },
          runState: 'IDLE',
        },
      },
      {
        id: 'vm-3',
        type: 'ktool',
        position: { x: 800, y: 150 },
        data: {
          type_id: 'media.convert_lossless_alac',
          stepNumber: 3,
          label: 'Passo 3: Salvar em Lossless (ALAC)',
          category: 'Mídia',
          description: 'Compacta para M4A sem perder 1 bit de qualidade.',
          inputs: [{ id: 'file', type: 'file', label: '🎵 Áudio WAV' }],
          outputs: [{ id: 'output_file', type: 'file', label: '✨ Arquivo M4A Pronto' }],
          config: { keep_source: true },
          runState: 'IDLE',
        },
      },
      {
        id: 'vm-4',
        type: 'ktool',
        position: { x: 1160, y: 150 },
        data: {
          type_id: 'system.notify',
          stepNumber: 4,
          label: 'Passo 4: Avisar no Windows',
          category: 'Sistema',
          description: 'Avisa quando o áudio estiver pronto.',
          inputs: [{ id: 'trigger', type: 'any', label: '⚡ Sinal de Término' }],
          outputs: [{ id: 'delivered', type: 'boolean', label: '✓ Alerta Enviado' }],
          config: {
            title: 'K-Tools Neo',
            message: 'Masterização de voz concluída com sucesso!',
          },
          runState: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'vme-1', source: 'vm-1', target: 'vm-2', sourceHandle: 'files', targetHandle: 'file', animated: true, style: { stroke: '#38bdf8', strokeWidth: 2 } },
      { id: 'vme-2', source: 'vm-2', target: 'vm-3', sourceHandle: 'output_file', targetHandle: 'file', animated: true, style: { stroke: '#c084fc', strokeWidth: 2 } },
      { id: 'vme-3', source: 'vm-3', target: 'vm-4', sourceHandle: 'output_file', targetHandle: 'trigger', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
  {
    id: 'tldv-meeting-export',
    name: '📝 Transcrição de Reunião tl;dv -> Resumo & Legendas',
    description: 'Processa o arquivo salvo do tl;dv e gera instantaneamente o resumo em Markdown e o arquivo de legendas SRT sincronizado.',
    category: 'Texto & Produtividade',
    icon: '📝',
    expectedOutput: {
      fileName: 'Transcricao_Reuniao.md',
      description: 'Documento Markdown estruturado com falantes, tópicos e horários',
      path: 'C:/Users/Public/Documents/Transcricao_Reuniao.md',
    },
    nodes: [
      {
        id: 'tl-1',
        type: 'ktool',
        position: { x: 80, y: 150 },
        data: {
          type_id: 'files.literal',
          stepNumber: 1,
          label: 'Passo 1: Arquivo HTML do tl;dv',
          category: 'Arquivos',
          description: 'Página da reunião salva do navegador.',
          inputs: [],
          outputs: [{ id: 'files', type: 'files', label: '📄 Arquivo HTML' }],
          config: { paths: 'reuniao_projeto_ktools.html' },
          runState: 'IDLE',
        },
      },
      {
        id: 'tl-2',
        type: 'ktool',
        position: { x: 440, y: 150 },
        data: {
          type_id: 'text.tldv_extract',
          stepNumber: 2,
          label: 'Passo 2: Extrair Transcrição Formatada',
          category: 'Texto',
          description: 'Converte falantes, timestamps e diálogos.',
          inputs: [{ id: 'file', type: 'file', label: '📄 Arquivo HTML' }],
          outputs: [
            { id: 'markdown', type: 'file', label: '📑 Documento Markdown' },
            { id: 'srt', type: 'file', label: '💬 Legendas SRT' },
          ],
          config: {},
          runState: 'IDLE',
        },
      },
      {
        id: 'tl-3',
        type: 'ktool',
        position: { x: 820, y: 150 },
        data: {
          type_id: 'system.notify',
          stepNumber: 3,
          label: 'Passo 3: Avisar no Windows',
          category: 'Sistema',
          description: 'Avisa quando o resumo e legendas estiverem prontos.',
          inputs: [{ id: 'trigger', type: 'any', label: '⚡ Sinal de Término' }],
          outputs: [{ id: 'delivered', type: 'boolean', label: '✓ Alerta Enviado' }],
          config: {
            title: 'K-Tools Neo',
            message: 'Transcrição extraída com sucesso em Markdown e SRT!',
          },
          runState: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'tle-1', source: 'tl-1', target: 'tl-2', sourceHandle: 'files', targetHandle: 'file', animated: true, style: { stroke: '#38bdf8', strokeWidth: 2 } },
      { id: 'tle-2', source: 'tl-2', target: 'tl-3', sourceHandle: 'markdown', targetHandle: 'trigger', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
  {
    id: 'disk-structure-audit',
    name: '📊 Auditoria de Pastas e Espaço em Disco',
    description: 'Audita pastas no computador ou na nuvem gerando inventário completo em planilha CSV e árvore ASCII visual.',
    category: 'Sistema & Auditoria',
    icon: '📊',
    expectedOutput: {
      fileName: 'Relatorio_Estrutura_Pastas.csv',
      description: 'Planilha detalhada com contagem de arquivos e tamanhos de diretórios',
      path: 'C:/Relatorios_KTools/Relatorio_Estrutura_Pastas.csv',
    },
    nodes: [
      {
        id: 'audit-1',
        type: 'ktool',
        position: { x: 80, y: 150 },
        data: {
          type_id: 'folder.literal',
          stepNumber: 1,
          label: 'Passo 1: Pasta para Auditar',
          category: 'Arquivos',
          description: 'Pasta local ou pasta do Google Drive/OneDrive.',
          inputs: [],
          outputs: [{ id: 'folder', type: 'folder', label: '📁 Pasta Selecionada' }],
          config: { path: 'C:/Projetos' },
          runState: 'IDLE',
        },
      },
      {
        id: 'audit-2',
        type: 'ktool',
        position: { x: 440, y: 150 },
        data: {
          type_id: 'filesystem.structure_report',
          stepNumber: 2,
          label: 'Passo 2: Mapear Árvore e Tamanhos',
          category: 'Arquivos',
          description: 'Gera inventário de espaço e arquivos.',
          inputs: [{ id: 'folder', type: 'folder', label: '📁 Pasta para Auditar' }],
          outputs: [
            { id: 'report_csv', type: 'file', label: '📑 Planilha CSV' },
            { id: 'tree_txt', type: 'file', label: '🌳 Desenho da Árvore' },
          ],
          config: { output_dir: 'C:/Relatorios_KTools' },
          runState: 'IDLE',
        },
      },
      {
        id: 'audit-3',
        type: 'ktool',
        position: { x: 800, y: 150 },
        data: {
          type_id: 'system.notify',
          stepNumber: 3,
          label: 'Passo 3: Avisar no Windows',
          category: 'Sistema',
          description: 'Avisa quando o relatório terminar de ser gerado.',
          inputs: [{ id: 'trigger', type: 'any', label: '⚡ Sinal de Término' }],
          outputs: [{ id: 'delivered', type: 'boolean', label: '✓ Alerta Enviado' }],
          config: {
            title: 'K-Tools Neo',
            message: 'Relatório de auditoria salvo em C:/Relatorios_KTools!',
          },
          runState: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'ae-1', source: 'audit-1', target: 'audit-2', sourceHandle: 'folder', targetHandle: 'folder', animated: true, style: { stroke: '#eab308', strokeWidth: 2 } },
      { id: 'ae-2', source: 'audit-2', target: 'audit-3', sourceHandle: 'report_csv', targetHandle: 'trigger', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
  {
    id: 'pdf-split-reorganize',
    name: '📕 Divisão Inteligente de Documentos PDF',
    description: 'Divide contratos, livros ou relatórios extensos em volumes menores e organizados.',
    category: 'PDF & Documentos',
    icon: '📕',
    expectedOutput: {
      fileName: 'Documento_Parte_1.pdf',
      description: 'Coleção de arquivos PDF repartidos de forma equilibrada',
      path: 'C:/Users/Public/Documents/PDFs_Divididos/Parte_1.pdf',
    },
    nodes: [
      {
        id: 'pdf-1',
        type: 'ktool',
        position: { x: 80, y: 150 },
        data: {
          type_id: 'files.literal',
          stepNumber: 1,
          label: 'Passo 1: Documento PDF',
          category: 'Arquivos',
          description: 'Arquivo PDF que precisa ser dividido.',
          inputs: [],
          outputs: [{ id: 'files', type: 'files', label: '📕 PDF Original' }],
          config: { paths: 'documento_extenso.pdf' },
          runState: 'IDLE',
        },
      },
      {
        id: 'pdf-2',
        type: 'ktool',
        position: { x: 440, y: 150 },
        data: {
          type_id: 'pdf.split.parts',
          stepNumber: 2,
          label: 'Passo 2: Dividir em Partes',
          category: 'PDF',
          description: 'Reparte em volumes com páginas equilibradas.',
          inputs: [{ id: 'file', type: 'file', label: '📕 PDF Original' }],
          outputs: [{ id: 'parts', type: 'files', label: '📚 Partes Divididas' }],
          config: { parts_count: 2 },
          runState: 'IDLE',
        },
      },
      {
        id: 'pdf-3',
        type: 'ktool',
        position: { x: 800, y: 150 },
        data: {
          type_id: 'system.notify',
          stepNumber: 3,
          label: 'Passo 3: Avisar no Windows',
          category: 'Sistema',
          description: 'Avisa quando as partes estiverem prontas.',
          inputs: [{ id: 'trigger', type: 'any', label: '⚡ Sinal de Término' }],
          outputs: [{ id: 'delivered', type: 'boolean', label: '✓ Alerta Enviado' }],
          config: {
            title: 'K-Tools Neo',
            message: 'PDF dividido com sucesso!',
          },
          runState: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'pdfe-1', source: 'pdf-1', target: 'pdf-2', sourceHandle: 'files', targetHandle: 'file', animated: true, style: { stroke: '#ef4444', strokeWidth: 2 } },
      { id: 'pdfe-2', source: 'pdf-2', target: 'pdf-3', sourceHandle: 'parts', targetHandle: 'trigger', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
  {
    id: 'python-script-pipeline',
    name: '🐍 Automação com Script Python (Filtrar e Processar)',
    description: 'Varre uma pasta de arquivos e passa a lista para um código Python customizado dentro do fluxo.',
    category: 'Automação & Script',
    icon: '🐍',
    expectedOutput: {
      fileName: 'Relatorio_Script_Processado.json',
      description: 'Resultado estruturado retornado pelo código Python',
      path: 'C:/Users/Public/KTools_Outputs/Relatorio_Script_Processado.json',
    },
    nodes: [
      {
        id: 'py-step-1',
        type: 'ktool',
        position: { x: 80, y: 150 },
        data: {
          type_id: 'folder.literal',
          stepNumber: 1,
          label: 'Passo 1: Pasta de Arquivos',
          category: 'Arquivos',
          description: 'Pasta onde estão os arquivos a processar.',
          inputs: [],
          outputs: [{ id: 'folder', type: 'folder', label: '📁 Pasta Selecionada' }],
          config: { path: 'C:/Downloads' },
          runState: 'IDLE',
        },
      },
      {
        id: 'py-step-2',
        type: 'ktool',
        position: { x: 440, y: 150 },
        data: {
          type_id: 'folder.scan_files',
          stepNumber: 2,
          label: 'Passo 2: Localizar Arquivos',
          category: 'Arquivos',
          description: 'Encontra os arquivos na pasta.',
          inputs: [{ id: 'folder', type: 'folder', label: '📁 Pasta para Varrer' }],
          outputs: [
            { id: 'files', type: 'files', label: '📚 Arquivos Encontrados' },
            { id: 'report', type: 'json', label: '📊 Relatório' },
          ],
          config: { extensions: 'mp4,wav,txt,json', recursive: true },
          runState: 'IDLE',
        },
      },
      {
        id: 'py-step-3',
        type: 'ktool',
        position: { x: 820, y: 150 },
        data: {
          type_id: 'script.python_run',
          stepNumber: 3,
          label: 'Passo 3: Script Python Customizado',
          category: 'Automação',
          description: 'Executa lógica em Python com a variável data.',
          inputs: [
            { id: 'data', type: 'any', label: '📥 Dados de Entrada' },
            { id: 'code', type: 'text', label: '📜 Código Python' },
          ],
          outputs: [
            { id: 'result', type: 'any', label: '✨ Resultado do Script' },
            { id: 'stdout', type: 'text', label: '💬 Saída do Print' },
          ],
          config: {
            code: "# Código Python integrado no K-Tools Neo\nprint(f'Recebidos {len(data or [])} arquivos para filtrar')\nresult = {'total_arquivos': len(data or []), 'processado': True}\noutputs['result'] = result",
          },
          runState: 'IDLE',
        },
      },
      {
        id: 'py-step-4',
        type: 'ktool',
        position: { x: 1200, y: 150 },
        data: {
          type_id: 'system.notify',
          stepNumber: 4,
          label: 'Passo 4: Avisar no Windows',
          category: 'Sistema',
          description: 'Notifica na tela que o script concluiu.',
          inputs: [{ id: 'trigger', type: 'any', label: '⚡ Sinal de Término' }],
          outputs: [{ id: 'delivered', type: 'boolean', label: '✓ Alerta Enviado' }],
          config: {
            title: 'K-Tools Neo — Script Python',
            message: 'Seu script Python foi executado com sucesso dentro do fluxo!',
          },
          runState: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'pye-1', source: 'py-step-1', target: 'py-step-2', sourceHandle: 'folder', targetHandle: 'folder', animated: true, style: { stroke: '#eab308', strokeWidth: 2 } },
      { id: 'pye-2', source: 'py-step-2', target: 'py-step-3', sourceHandle: 'files', targetHandle: 'data', animated: true, style: { stroke: '#38bdf8', strokeWidth: 2 } },
      { id: 'pye-3', source: 'py-step-3', target: 'py-step-4', sourceHandle: 'result', targetHandle: 'trigger', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
  {
    id: 'youtube-download-and-join',
    name: '🎬 Baixar do YouTube e Juntar Vídeos (Pipeline Automático)',
    description: 'Baixa uma playlist ou partes de vídeo do YouTube e junta automaticamente em um único arquivo final.',
    category: 'YouTube & Vídeo',
    icon: '🔻',
    expectedOutput: {
      fileName: 'Video_Unificado.mp4',
      description: 'Vídeo final com todas as partes baixadas unidas',
      path: 'C:/Users/Public/KTools_Outputs/Video_Unificado.mp4',
    },
    nodes: [
      {
        id: 'yt-step-1',
        type: 'ktool',
        position: { x: 100, y: 150 },
        data: {
          type_id: 'youtube.download',
          stepNumber: 1,
          label: 'Passo 1: Baixar do YouTube',
          category: 'Download',
          description: 'Baixa o vídeo ou as partes da playlist.',
          inputs: [
            { id: 'url', type: 'text', label: '🔗 Link do Vídeo ou Playlist' },
          ],
          outputs: [
            { id: 'files', type: 'files', label: '📚 Arquivos Baixados' },
            { id: 'folder', type: 'folder', label: '📁 Pasta de Destino' },
          ],
          config: {
            url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            media_type: 'video',
            quality: 'best',
          },
          runState: 'IDLE',
        },
      },
      {
        id: 'yt-step-2',
        type: 'ktool',
        position: { x: 550, y: 150 },
        data: {
          type_id: 'media.join_videos',
          stepNumber: 2,
          label: 'Passo 2: Juntar Vídeos em 1 Só',
          category: 'Mídia',
          description: 'Une todas as partes baixadas em um único vídeo.',
          inputs: [
            { id: 'videos', type: 'files', label: '📚 Vídeos para Juntar' },
          ],
          outputs: [
            { id: 'video', type: 'video', label: '🎬 Vídeo Final' },
          ],
          config: {
            output_format: 'mp4',
          },
          runState: 'IDLE',
        },
      },
      {
        id: 'yt-step-3',
        type: 'ktool',
        position: { x: 980, y: 150 },
        data: {
          type_id: 'system.notify',
          stepNumber: 3,
          label: 'Passo 3: Avisar no Windows',
          category: 'Sistema',
          description: 'Notifica na tela que o download e união terminaram.',
          inputs: [
            { id: 'trigger', type: 'any', label: '⚡ Sinal de Término' },
          ],
          outputs: [
            { id: 'delivered', type: 'boolean', label: '✓ Alerta Enviado' },
          ],
          config: {
            title: 'K-Tools Neo — YouTube Pipeline',
            message: 'O download e a união do vídeo foram concluídos com sucesso!',
          },
          runState: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'yte-1', source: 'yt-step-1', target: 'yt-step-2', sourceHandle: 'files', targetHandle: 'videos', animated: true, style: { stroke: '#ef4444', strokeWidth: 2 } },
      { id: 'yte-2', source: 'yt-step-2', target: 'yt-step-3', sourceHandle: 'video', targetHandle: 'trigger', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
];
